### ISSUE TITLE
Peer Review By - DreamJobs

### ISSUE THREAD

**Issue by SohanicX** [INFO-526-FA24/project-2-4x4#1]
The following is the peer review of the project proposal by DreamJobs. The team members that participated in this review are

[Meghashree N] - @[lucifer970901]

[Sohan Shankar arasavilli] - @[SohanicX]

[Ram Teja Vangari]  - @[Ramtejavangar]

**Describe the goal of the project.**
The goal of this project is to explore and demonstrate the BrailleR package in R, which aids accessibility by generating text descriptions of visualizations that are accessible to visually impaired users. While the goal is clear, it might be too narrow in scope, focusing solely on BrailleR without exploring alternative accessibility tools or methods for making visualizations accessible. This could limit the depth of the project and miss opportunities to compare BrailleR’s effectiveness against other solutions and if BrailleR really serves its intended purpose.

**Describe the data used or collected.**
The proposal indicates that the specific data used for the project is not the focus, as the aim is to demonstrate BrailleR's functionality across various visualization types. Since the data itself is not a focus, there’s a risk that less care will be taken in selecting datasets that genuinely represent the typical visualizations where accessibility is needed. Choosing arbitrary datasets might not fully capture the challenges that visually impaired users face in more complex or nuanced data scenarios. 

**Describe how the research question will be answered, e.g. what approaches / methods will be used.**
There is no mention of any particular question they trying to answer here. Its vaguely straightforward: using the BrailleR package to generate text descriptions for three types of plots.
The approach primarily revolves around demonstration rather than testing or analysis of BrailleR's effectiveness. Without user feedback or quantitative assessment of the text descriptions’ quality, it may be hard to conclude how well BrailleR actually serves visually impaired users.

**Is there anything that is unclear from the proposal?**
The proposal seems too basic or introductory, as it doesn't clearly define the metrics or criteria by which BrailleR’s descriptions will be evaluated. This makes it challenging to assess if BrailleR is genuinely effective, and without clear evaluation criteria, it might read more like a tutorial than a research project.
Data Sources: There is no where any mention of data source. It would be helpful to specify potential sources for the datasets to reassure that the data will be diverse and suitable for the intended visualizations and evaluation.

**Provide constructive feedback on how the team might be able to improve their project.**
The timeline is somewhat general and doesn’t account for unexpected challenges, such as issues with BrailleR’s integration on complex plots. Without testing timelines or contingency plans, the team might struggle if they encounter difficulties or if BrailleR falls short on certain types of visualizations.
Since BrailleR is not widely known, briefly explaining its significance for visually impaired users in more detail could make the project’s impact clearer.
Timeline Refinement: Adding a timeline for the stages of each task (e.g., when plots should be completed) and specifying checkpoints for incorporating BrailleR’s descriptions will help ensure progress.
The team should include the inline code for better understanding & plots startegies they are planning to use.

**What aspect of this project are you most interested in and would like to see highlighted in the presentation.**
A comparison of BrailleR-generated text descriptions with visual interpretations of the plots, to see how well the tool conveys plot information to visually impaired users.
Demonstrations of how BrailleR performs with different plot types (time series, histograms, regression plots) to observe its versatility and potential limitations.
Focusing too heavily on demonstrating BrailleR’s different plot types may miss the deeper question of whether the text descriptions are genuinely accessible and helpful to the target audience. Additionally, if time constraints limit the presentation, important discussions about the effectiveness and potential limitations of BrailleR may be skipped.

**Provide constructive feedback on any issues with file and/or code organization.**
The project document structure seems sound, but specifying where each team member will store and organize their datasets, plots, and scripts would improve organization. This will make it easier to integrate their contributions into a cohesive final product.
Without a standardized structure or naming conventions across team members, the project may become disorganized, especially if each member is working on separate datasets and plots. This could lead to challenges when integrating the individual components into a cohesive final report or presentation.

**(Optional) Any further comments or feedback?**
Examples of BrailleR Output: Including examples of BrailleR-generated text descriptions (if possible) could make the accessibility features clearer for reviewers unfamiliar with BrailleR.
Testing BrailleR with feedback from visually impaired users could add further depth to the research, as it would offer real-world insights on the package’s utility and provide valuable insights into how well BrailleR serves its intended purpose.
The project might lack depth if it solely focuses on BrailleR without assessing other methods or tools for accessibility in data visualization. This may limit its contributions to the broader topic of accessibility in data science, as the project won’t provide a comparative analysis of different approaches.

**Comment by jaelynkapuaioane** [comment]
Thank you for your feedback. We've updated our proposal to include a research question and a more specific description of what we are measuring within BrailleR as well as the datasets we are using and what plot we are creating with each dataset. We have also added metrics for accessibility of BrailleR
