### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by Twhite13** [INFO-526-FA24/project-2-4x4#2]
Reviewing Team Name:  InfoCrew

Team Members: 
Aastha Prasad - mausam20
Tallapaneni Venkateshwara Chowdary - tallapaneniv
Trayvion White-Austin - Twhite13

**Goal** 

Their goal  is to explore and demonstrate the functionality of the BrailleR package in R and how it will be beneficial for users. BrailleR is designed to make data visualizations more accessible for visually impaired users by creating text descriptions that can be read by screen readers. 

**Data used** 

The project will use multiple datasets suitable for different types of plots ( time series, histogram, and regression). The specific datasets are chosen based on the types of visualizations the team wants to create, so not a specific data set will be used.

**Approaches/methods used to answer the research question** 

The team plans to use R to create various plots like time series, histogram, regression plots while using different datasets. Then, they will apply the BrailleR package to generate text descriptions of these plots, demonstrating how visually impaired users can access the information contained in visualizations.

**Anything unclear from the proposal** 

What kind of variables would be used, and or what would be the theme of your visualizations.

**Aspect of the project most interested in and would like highlighted in the presentation**

we are most interested in seeing the specific text descriptions generated by BrailleR for each plot type and understanding how well these descriptions portray the visual made.

**Constructive feedback on issues with file and/or code organization**

Include a Readme.md for the GitHub repo detailing the files on there aside from that. I am very much looking forward how this project will turn out.

**(Optional) Further comments or feedback**
no

**Comment by jaelynkapuaioane** [comment]
Thank you for your feedback. We have included a description of the datasets we are using and what variables are being used

**Comment by annahoju** [comment]
Hello team 4x4 - this suggestion from your reviewer is a good one "Include a Readme.md for the GitHub repo detailing the files" Please do this.
