### ISSUE TITLE
Instructor review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-4x4#3]
Hello team 4X4 - 

Very exciting project proposal. Based on the proposal, I think that you have thorough consider many aspects of the project and are set up for success.  One mention would be to consider, as I said in the Slack message, what your main goals of the project are. Your research question addresses this initial curiousity and I encourage you to keep that in focus.  Otherwise your overall write up/poster and story may not be cohesive. 

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |    3    |
| Proposal | 5         |   5     |
| Workflow | 1         |    1    |
| Teamwork | 1         |     1   |
| Total    | 10        |   10     |

**Comment by jaelynkapuaioane** [comment]
Thank you for the feedback - we've began discussing the the poster presentation, but didn't realize that should be included in the proposal.
