### ISSUE TITLE
MOCK iShowcase - Instructor feedback 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-4x4#4]
When did the package release? Add a little bit more about BrailleR. 
Add a label over or change font type to indicate what is made by the package.  (suggested italicized?)

**Comment by annahoju** [comment]
Add indication where you think (as humans) the machine could improve the alt text.

**Comment by tanmaynaik11** [comment]
Thank You, the changes have been made in the poster as suggested.
